# Generated by Django 3.2.12 on 2022-02-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(max_length=3)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('assigned_doctor', models.CharField(max_length=200)),
                ('check_in_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
