# Generated by Django 3.2.12 on 2022-02-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_admin_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='role',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
    ]
