# Generated by Django 3.2.12 on 2022-02-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_patient_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.CharField(default='admin', max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(default='doctor', max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='role',
            field=models.CharField(default='patient', max_length=200),
        ),
    ]
