# Generated by Django 3.2.12 on 2022-02-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220218_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='classification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
