# Generated by Django 3.2.12 on 2022-02-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_report_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(upload_to='static/images/% Y/% m/ 19/'),
        ),
    ]
