# Generated by Django 3.2.12 on 2022-02-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_patient_check_in_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.CharField(default='default', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_num',
            field=models.CharField(default='default', max_length=13),
            preserve_default=False,
        ),
    ]
