# Generated by Django 3.2.12 on 2022-02-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20220219_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='assigned_doctor',
            field=models.CharField(max_length=201),
        ),
    ]
