# Generated by Django 3.2.12 on 2022-02-19 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_patient_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='first_name',
            new_name='patient_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
    ]
