# Generated by Django 3.2.12 on 2022-02-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20220219_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pathologist',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
    ]
