# Generated by Django 3.2.12 on 2022-02-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_report_pathologist'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
    ]
